return {
  "bashls",                --Bash
  "ast_grep",              --Many
  "cssls",                 --CSS
  "cssmodules_ls",         --CSS
  "tailwindcss",           --CSS
  "emmet_language_server", --Emmet
  "html",                  --HTML
  "hyprls",                --Hyprland
  "eslint",                --Javascript
  "harper_ls",             --Javascript
  "ts_ls",                 --Javascript
  "jsonls",                --Json
  "lua_ls",                --Lua
  "marksman",              --Markdown
  "zk",                    --Markdown
  "pyright",               --Python
  "ruff",                  --Python
  "somesass_ls",           --SCSS
  "stylelint_lsp",         --Stylint
}
