DOTFILES_DIR="$HOME/arch-hypr-dots"
NVIM_DIRS=(
  "$HOME/.config/nvim"
  "$HOME/.local/share/nvim"
  "$HOME/.local/state/nvim"
  "$HOME/.cache/nvim"
)
NVM_VERSION="v0.40.3"
GEANY_DIRS=(
  "$HOME/.config/geany/colorschemes"
  "$HOME/.config/geany/plugins"
)
