[default]
# path = "~/arch-hypr-dots/home/user/wallpapers/samurai/"
path = "~/arch-hypr-dots/home/user/wallpapers/samurai/red_samurai.jpg"
# duration = "10m"
# exec = "~/arch-hypr-dots/home/user/.config/wpaperd/exec.sh"

["re:HDMI-A-\\d"]
group = 1
